## 雑記 

In [1]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(10,step=2)

array([0, 2, 4, 6, 8])

In [9]:
np.random.randn(10)

array([ 1.54957655,  0.00681998, -2.22673916, -1.01525334, -0.19941898,
        0.70421935, -1.2225714 ,  1.81677972, -0.54902759,  0.66046993])

In [14]:
np.random.binomial(n=100, p=0.1, size=(10))


array([11, 10, 12, 16,  7,  7,  8, 12, 11, 10])

In [15]:
np.random.poisson(lam=10,size=(10))

array([ 9, 11,  8,  9,  9,  3, 10,  8, 11, 13])

In [16]:
np.random.randint(low=0,high=2,size=10)

array([0, 0, 0, 1, 0, 0, 0, 1, 1, 0])

In [17]:
np.arange(6).reshape((2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
np.arange(2*3*4*5).reshape(2,3,4,5)

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

In [20]:
x=np.array([[1,2,3],[4,5,6]])

In [21]:
x=np.arange(9).reshape((3,3))

In [22]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
x[:,1]

array([1, 4, 7])

In [24]:
x[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [25]:
x[:,1:]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [28]:
x[:,:2]

array([[0, 1],
       [3, 4],
       [6, 7]])

In [29]:
x=np.arange(9).reshape((3,3))

In [30]:
y=np.eye(3)

In [32]:
x[x>=5]

array([5, 6, 7, 8])

In [33]:
x[(x>=5)&(x<8)]

array([5, 6, 7])

In [36]:
x[y==1]

array([0, 4, 8])

In [37]:
x[x<5]=0

In [39]:
x

array([[0, 0, 0],
       [0, 0, 5],
       [6, 7, 8]])

In [40]:
x[x>=5]=1

In [41]:
x


array([[0, 0, 0],
       [0, 0, 1],
       [1, 1, 1]])

In [53]:
x=np.array([[1,2,3],[4,np.nan,5],[6,7,8]])

In [43]:
x

array([[ 1.,  2.,  3.],
       [ 4., nan,  5.],
       [ 6.,  7.,  8.]])

In [45]:
x[np.isnan(x)]=0

In [47]:
x

array([[1., 2., 3.],
       [4., 0., 5.],
       [6., 7., 8.]])

In [49]:
x[np.isnan(x)]=np.nanmean(x)
x

array([[1., 2., 3.],
       [4., 0., 5.],
       [6., 7., 8.]])

In [52]:
x[~np.isnan(x).any(axis=1)]

array([[1., 2., 3.],
       [6., 7., 8.]])

In [54]:
np.ma.compress_cols(np.ma.masked_invalid(x))

array([[1., 3.],
       [4., 5.],
       [6., 8.]])

In [55]:
x1 = np.arange(start=0, stop=3)

In [56]:
x2 = np.arange(start=3, stop=6)


In [57]:
np.vstack([x1,x2])

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
np.hstack([x1,x2])

array([0, 1, 2, 3, 4, 5])

In [59]:
np.r_[x1,x2]

array([0, 1, 2, 3, 4, 5])

In [60]:
np.dstack([x1,x2])

array([[[0, 3],
        [1, 4],
        [2, 5]]])

In [61]:
np.c_[x1,x2]

array([[0, 3],
       [1, 4],
       [2, 5]])

In [63]:
np.vstack([x1,x2]).T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [64]:
x=np.arange(10)

In [65]:
x.sum()

45

In [66]:
np.sum(x)

45

In [67]:
x.mean()

4.5

In [68]:
np.mean(x)

4.5

In [69]:
np.var(x)

8.25

In [70]:
np.std(x)

2.8722813232690143

In [71]:
x=x.reshape((2,5))

In [72]:
np.mean(x,axis=1)

array([2., 7.])

In [74]:
np.mean(x,axis=0)

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [75]:
x=np.arange(5)*2

In [76]:
np.sort(x)

array([0, 2, 4, 6, 8])

In [77]:
np.sort(x)[::-1]

array([8, 6, 4, 2, 0])

In [78]:
np.sort(x)[-3:][::-1]

array([8, 6, 4])

In [79]:
np.argsort(x)

array([0, 1, 2, 3, 4])

In [80]:
x = np.arange(5)

In [89]:
vf = np.vectorize(lamda: x: x*x)
vf(x)

SyntaxError: invalid syntax (<ipython-input-89-44f43939c4a0>, line 1)

In [90]:
class NamedArray(object):
    
    def __init__(self, name, values):
        self.name = name
        self.values = np.array(values)
        
            
    def __len__(self):
        return len(self.values)
        
    def __repr__(self):
        return 'NamedArray: {0}: {1}'.format(self.name, self.values)


In [99]:
n = NamedArray('x', [1, 2, 3])

In [100]:
n

NamedArray: x: [1 2 3]

In [101]:
n.__repr__()

'NamedArray: x: [1 2 3]'

In [102]:
n.__len__()

3

In [103]:
len(n)

3