## 100 numpy exercises

# 初心者向けサイト
http://wbhappy.hatenablog.jp/entry/2015/02/06/210000
http://rest-term.com/archives/2999/
https://qiita.com/takaaki5564/items/451d9d6c319f76758a9d
# クラス
http://diveintopython3-ja.rdy.jp/special-method-names.html

## 1,numpyパッケージをnpの名前でインポート

In [14]:
import numpy as np

## 2,numpyのバージョンと構造を表示

In [4]:
print(np.__version__)
np.show_config()

1.14.0
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/satoutakumi/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/satoutakumi/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/satoutakumi/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/satoutakumi/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/satoutakumi/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/satoutakumi/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/satoutakumi/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/satoutakumi/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
 

## 3,サイズ10のゼロベクトルを作成する

In [16]:
z=np.zeros(10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 4,配列のメモリ容量を見る

In [18]:
Z=np.zeros((10,10))

In [19]:
print("%d bytes"%(Z.size*Z.itemsize))

800 bytes


## 5,コマンドラインからnumpy add関数のドキュメントを取得する方法は？

In [20]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


## 6,5つ目の要素が1で、他の値が0であるサイズ10のベクトルを作成する

In [23]:
Z=np.zeros(10)
Z[4]=1

In [24]:
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 7,10から49までの要素を持つベクトルを作成

In [25]:
Z=np.arange(10,50)

In [26]:
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 8,ベクトル要素を逆転させる

In [27]:
Z=np.arange(50)
Z=Z[::-1]

In [28]:
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


## 9,0から8を要素に持つ3*3の行列を作成する

In [30]:
Z=np.arange(9).reshape(3,3)

In [31]:
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 10,0ではない要素を検索する

In [32]:
nz=np.nonzero([1,2,0,0,4,0])

In [33]:
print(nz)

(array([0, 1, 4]),)


## 11,3*3の単位行列を作成する

In [35]:
Z=np.eye(3)

In [ ]:
print(Z)

## 12,3×3×3の乱数要素の配列を作成する

In [37]:
Z=np.random.random((3,3,3))

In [38]:
print(Z)

[[[0.49296474 0.88857457 0.44205907]
  [0.94401511 0.2042374  0.41767786]
  [0.14358995 0.12137678 0.82607988]]

 [[0.45353104 0.29218167 0.03297664]
  [0.42830174 0.80190286 0.64163096]
  [0.69013322 0.72972896 0.7669189 ]]

 [[0.48033225 0.3568582  0.78988607]
  [0.3462539  0.66852932 0.36978115]
  [0.98106431 0.17229289 0.67320306]]]


## 13, 10*10の乱数要素配列を作成し、最大値、最小値を検索する

In [39]:
Z=np.random.random((10,10))
Zmin,Zmax=Z.min(),Z.max()

In [40]:
print(Zmin,Zmax)

0.01029759587442447 0.9965922637791665


## 14,大きさ30の乱数ベクトルを作成し、その平均をとる

In [21]:
Z=np.random.random(30)
m=Z.mean()

0.4739090952844566


In [41]:
print(m)

0.4414994856476987


## 15, 縁が1 、内部が0の二次元配列を作成する

In [43]:
Z=np.ones((10,10))
Z[1:-1,1:-1]=0

In [44]:
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 16, 既存の配列の縁に0の縁を追加する

In [45]:
Z=np.ones((5,5))
Z=np.pad(Z,pad_width=1,mode='constant',constant_values=0)

In [46]:
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## 17,以下の表記の結果は？

In [25]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)

nan
False
False
nan
False


## 18,対角項の一つ下の値が1,2,3,4である5*5の行列を作成する

In [47]:
Z=np.diag(1+np.arange(4),k=-1)

In [48]:
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## 19, 8*8の行列を作成し、市松模様で埋める

In [49]:
Z=np.zeros((8,8),dtype=int)
Z[1::2,::2]=1
Z[::2,1::2]=1

In [50]:
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 20,(6,7,8)の型の配列を考えた時、100番目の(x,y,z)の要素は？

In [10]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


## 21,tile関数を用いて8*8の市松模様行列を作る

In [51]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))

In [52]:
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 22,5*5の乱数行列を規格化する

In [54]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)

In [55]:
print(Z)

[[0.04973902 0.78893962 0.2820745  0.31614178 0.4024656 ]
 [0.7326271  0.75887899 0.91094982 0.23679774 0.93713426]
 [0.98882328 1.         0.67955807 0.18641917 0.49830707]
 [0.03896016 0.         0.67224384 0.2683047  0.26557255]
 [0.96512898 0.93739637 0.3633263  0.11535098 0.11675175]]


## 23,

In [14]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

## 24,5*3の行列と3*2の行列をかける

In [15]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


##  25,与えられた一次元配列の3~8要素の符号を変える

In [16]:

# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


## 26,以下のスクリプトの結果は？

In [17]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


## 27,整数ベクトルを考えた時、以下のどの表記が正しいか

In [18]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: Integers to negative integer powers are not allowed.

## 28,以下の結果は？ 

In [19]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/Users/satoutakumi/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/Users/satoutakumi/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


## 29,float型の配列の小数点以下切り下げをする方法

In [20]:
# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[10. 10. -2. 10.  5. -4.  1.  2. -3. -3.]


## 30,二つの配列から同じ値を見つける方法

In [21]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 1 3 4 7 8]


## 31,numpyの全ての警告を無視する方法

In [22]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

SyntaxError: invalid syntax (<ipython-input-22-0437b6d2f8fa>, line 8)

## 32,以下の表現は正しいか？

In [23]:
np.sqrt(-1) == np.emath.sqrt(-1)

/Users/satoutakumi/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

## 33,昨日、今日、明日の日にちを得る手法

In [25]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2018-04-11
2018-04-12
2018-04-13


## 34,2016年7月に対応する全ての日時を得る手法

In [26]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


## 35, ((A+B)*(-A/2))を正しく計算する方法(コピーを使わない)

In [27]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

## 36, 乱数配列から整数部分を抜き取る5つの方法

In [28]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[2. 1. 0. 3. 6. 5. 3. 4. 8. 7.]
[2. 1. 0. 3. 6. 5. 3. 4. 8. 7.]
[2. 1. 0. 3. 6. 5. 3. 4. 8. 7.]
[2 1 0 3 6 5 3 4 8 7]
[2. 1. 0. 3. 6. 5. 3. 4. 8. 7.]


## 37,行の値が0~4の5*5行列を作成する 

In [29]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## 38,10個の整数を生成する関数を作成し、配列を作る際に使う

In [30]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## 39,0~1の値を格納したサイズ10のベクトルを作成する。（0,1は含まない）

In [31]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


https://deepage.net/features/numpy-linspace.html

## 40,乱数を格納したサイズ10のベクトルを作成し、小さい順に並べる

In [32]:
Z=np.random.random(10)
Z.sort()
print(Z)

[0.01410237 0.07584196 0.17490852 0.2548823  0.5018627  0.66007391
 0.69475779 0.71558508 0.72120091 0.81031562]


## 41,np.sumよりも早く小さな配列要素を足し合わせる方法 

In [33]:
Z = np.arange(10)
np.add.reduce(Z)

45

##  42,二つの乱数配列A,Bが等しいか検討する

In [34]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


## 43,不変配列を作成する（読み取り専用）

In [35]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

## 44, デカルト座標を表した10*2の乱数行列を極座標に変換する

In [36]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.90387907 0.70750352 0.82292715 1.07163744 0.66359008 0.40579268
 0.27382563 0.56111697 0.92337161 0.68860122]
[0.70141209 0.2158255  0.53671768 0.93457967 0.96601166 0.10282549
 0.09749518 1.33515428 0.86502439 0.56437924]


## 45,サイズ10の乱数ベクトルを作成し、最大値を0に置き換える

In [37]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.90794388 0.80991313 0.01976632 0.40246101 0.66164125 0.81402523
 0.93656103 0.91544365 0.91896699 0.        ]


##  46,[0,1]*[0,1]の範囲にあるx,y座標の格子配列を作成する

In [38]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)　

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


##  47,与えられた二つの配列X、Yについてコーシー行列C (Cij =1/(xi - yj))を作成する

In [39]:
# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


## 48, それぞれのスカラー型の記号表記できる最小値、最大値を表示する

In [40]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


## 49,配列の全ての値を表示する方法

In [3]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## 50,ベクトル内の最も近い値（与えられたスカラー量）を見つける方法

In [4]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

86


## 51,位置(x,y)色(r,g,b)を表す格子配列を作る方法

In [5]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


## 52,座標を表す(100,2)型の乱数ベクトルを考え、二点の距離を測る

In [6]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.68493474 0.85751709 0.56407475 0.33350427 0.89072724
  0.75774738 0.62909346 0.14618969 0.56052825]
 [0.68493474 0.         0.30014449 0.40160472 0.51669208 0.32518611
  0.1284727  0.07694959 0.73818701 0.37773032]
 [0.85751709 0.30014449 0.         0.69952722 0.5854197  0.55545458
  0.17247191 0.28877665 0.8631445  0.67545444]
 [0.56407475 0.40160472 0.69952722 0.         0.61707753 0.39032331
  0.52979368 0.41754679 0.68475999 0.02414691]
 [0.33350427 0.51669208 0.5854197  0.61707753 0.         0.80980051
  0.53717426 0.44212486 0.28720909 0.60116628]
 [0.89072724 0.32518611 0.55545458 0.39032331 0.80980051 0.
  0.40565673 0.39858249 0.98060574 0.37764832]
 [0.75774738 0.1284727  0.17247191 0.52979368 0.53717426 0.40565673
  0.         0.13657046 0.78984723 0.50585146]
 [0.62909346 0.07694959 0.28877665 0.41754679 0.44212486 0.39858249
  0.13657046 0.         0.67281419 0.39341865]
 [0.14618969 0.73818701 0.8631445  0.68475999 0.28720909 0.98060574
  0.78984723 0.67281

## 53,32ビットのfloat型の配列をその場で32ビットの整数配列に変更する方法

In [7]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


## 54,以下のファイルはどうやって読む？

In [8]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


## 55,列挙されたnumpy配列と同等のものは何？

In [9]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


## 56, 一般的な二次元ガウシアン配列を生成する

In [10]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

## 57, 二次元配列にp要素をランダムに配置する方法

In [11]:
# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## 58,行列の各行の平均を引く

In [12]:
# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.12508091  0.51935037  0.2515258  -0.4303889  -0.40982887  0.42675646
  -0.26502269  0.44395606 -0.28937173 -0.1218956 ]
 [-0.12947807  0.34483245 -0.15476636 -0.01478072  0.00415741  0.20934306
   0.40186216 -0.36210253 -0.01406406 -0.28500336]
 [-0.07109664  0.10932553 -0.15095738 -0.2630261  -0.03470039  0.49073183
   0.0529792   0.11105902 -0.046118   -0.19819707]
 [-0.27295925  0.12204345  0.18682201 -0.36423627  0.07153667 -0.334351
   0.45199787 -0.15925301  0.51674984 -0.21835031]
 [-0.21407788  0.11409541 -0.21545737  0.15435569  0.17068287 -0.24839039
  -0.15652212  0.36213187 -0.13766457  0.17084649]]


## 59,n番目の列によって配列を並び替える方法

In [13]:
# Author: Steve Tjoa

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[0 9 6]
 [2 3 4]
 [7 7 7]]
[[2 3 4]
 [7 7 7]
 [0 9 6]]


## 60,与えられた二次元配列にnull列があるかどうか知る方法 

In [3]:
 # Author: Warren Weckesser

Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


## 61, 配列内の与えられた値から最も近い値を探す

In [4]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4414994856476987


## 62, (1,3)型と(3,1)型の配列を考え、イテレータを用いて足し算を行う

In [5]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


## 63,nameという名前の属性を持つ配列クラスを定義する

In [6]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


## 64, 与えられたベクトルを考え、二つ目のベクトルのインデックスの要素の個数につき1足していく方法

In [8]:
# Author: Brett Olsen

Z = np.ones(10)
print(Z)
I = np.random.randint(0,len(Z),20)
print(I)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[8 7 6 4 0 8 9 4 7 2 1 4 9 7 9 8 3 2 8 1]
[2. 3. 3. 2. 4. 1. 2. 4. 5. 4.]
[3. 5. 5. 3. 7. 1. 3. 7. 9. 7.]


## ＊65,Xベクトルの要素をIのリストのインデックスに基づいてF配列に累積する方法

In [12]:

# Author: Alan G Isaac

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


## 66,

In [13]:
# Author: Nadav Horesh

w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8
