## 100 numpy exercises

# 初心者向けサイト
http://wbhappy.hatenablog.jp/entry/2015/02/06/210000
http://rest-term.com/archives/2999/
https://qiita.com/takaaki5564/items/451d9d6c319f76758a9d

## 1,numpyパッケージをnpの名前でインポート

In [76]:
import numpy as np

## 2,numpyのバージョンと構造を表示

In [4]:
print(np.__version__)
np.show_config()

1.14.0
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/satoutakumi/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/satoutakumi/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/satoutakumi/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/satoutakumi/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/satoutakumi/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/satoutakumi/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/satoutakumi/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/satoutakumi/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
 

## 3,サイズ10のゼロベクトルを作成する

In [16]:
z=np.zeros(10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 4,配列のメモリ容量を見る

In [18]:
Z=np.zeros((10,10))

In [19]:
print("%d bytes"%(Z.size*Z.itemsize))

800 bytes


## 5,コマンドラインからnumpy add関数のドキュメントを取得する方法は？

In [56]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


## 6,5つ目の要素が1で、他の値が0であるサイズ10のベクトルを作成する

In [23]:
Z=np.zeros(10)
Z[4]=1

In [24]:
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 7,10から49までの要素を持つベクトルを作成

In [25]:
Z=np.arange(10,50)

In [26]:
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 8,ベクトル要素を逆転させる

In [27]:
Z=np.arange(50)
Z=Z[::-1]

In [28]:
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


## 9,0から8を要素に持つ3×3の行列を作成する

In [30]:
Z=np.arange(9).reshape(3,3)

In [31]:
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 10,0ではない要素を検索する

In [32]:
nz=np.nonzero([1,2,0,0,4,0])

In [33]:
print(nz)

(array([0, 1, 4]),)


## 11,3×3の単位行列を作成する

In [35]:
Z=np.eye(3)

In [ ]:
print(Z)

## 12,3×3×3の乱数要素の配列を作成する

In [37]:
Z=np.random.random((3,3,3))

In [38]:
print(Z)

[[[0.49296474 0.88857457 0.44205907]
  [0.94401511 0.2042374  0.41767786]
  [0.14358995 0.12137678 0.82607988]]

 [[0.45353104 0.29218167 0.03297664]
  [0.42830174 0.80190286 0.64163096]
  [0.69013322 0.72972896 0.7669189 ]]

 [[0.48033225 0.3568582  0.78988607]
  [0.3462539  0.66852932 0.36978115]
  [0.98106431 0.17229289 0.67320306]]]


## 13, 10×10の乱数要素配列を作成し、最大値、最小値を検索する

In [39]:
Z=np.random.random((10,10))
Zmin,Zmax=Z.min(),Z.max()

In [40]:
print(Zmin,Zmax)

0.01029759587442447 0.9965922637791665


## 14,大きさ30の乱数ベクトルを作成し、その平均をとる

In [21]:
Z=np.random.random(30)
m=Z.mean()

0.4739090952844566


In [41]:
print(m)

0.4414994856476987


## 15, 縁が1 、内部が0の二次元配列を作成する

In [43]:
Z=np.ones((10,10))
Z[1:-1,1:-1]=0

In [44]:
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 16, 既存の配列の縁に0の縁を追加する

In [45]:
Z=np.ones((5,5))
Z=np.pad(Z,pad_width=1,mode='constant',constant_values=0)

In [46]:
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## 17,以下の表記の結果は？

In [25]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)

nan
False
False
nan
False


## 18,対角項の一つ下の値が1,2,3,4である5×5の行列を作成する

In [47]:
Z=np.diag(1+np.arange(4),k=-1)

In [48]:
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## 19, 8×8の行列を作成し、市松模様で埋める

In [49]:
Z=np.zeros((8,8),dtype=int)
Z[1::2,::2]=1
Z[::2,1::2]=1

In [50]:
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 20,(6,7,8)の型の配列を考えた時、100番目の(x,y,z)の要素は？

In [10]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


## 21,tile関数を用いて8×8の市松模様行列を作る

In [51]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))

In [52]:
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 22,5×5の乱数行列を規格化する

In [54]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)

In [55]:
print(Z)

[[0.04973902 0.78893962 0.2820745  0.31614178 0.4024656 ]
 [0.7326271  0.75887899 0.91094982 0.23679774 0.93713426]
 [0.98882328 1.         0.67955807 0.18641917 0.49830707]
 [0.03896016 0.         0.67224384 0.2683047  0.26557255]
 [0.96512898 0.93739637 0.3633263  0.11535098 0.11675175]]


## 23,色を4つの符号なしバイト（RGBA）として記述するカスタムdtypeを作成

In [14]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

## 24,5×3の行列と3×2の行列をかける

In [57]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))

In [58]:
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))

##  25,与えられた一次元配列の3~8要素の符号を変える

In [62]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1

In [63]:
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


## 26,以下のスクリプトの結果は？

In [77]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#https://stackoverflow.com/questions/42955201/python-numpy-range-and-sum-1?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

#最初の行は、0 + 1 + 2 + 3 + 4 +（ - 1）と等価です。 3行目は、軸= -1で0 + 1 + 2 + 3 + 4に相当します。

## 27,整数ベクトルを考えた時、以下のどの表記が正しいか

In [78]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: Integers to negative integer powers are not allowed.

In [79]:
Z**Z

ValueError: Integers to negative integer powers are not allowed.

In [80]:
2 << Z >> 2

array([                 0,                  1,                  2,
                        4, 576460752303423488, 288230376151711744,
       144115188075855872,  72057594037927936,  36028797018963968,
                      256,                512])

#https://stackoverflow.com/questions/38491204/numpy-and-operators
#演算子<<と>>はビットシフト演算子です（それぞれ左と右です）。 特定の例（<<付き）では、配列要素ごとにx = x * 2 ^ zを実行しています。その結果、出力が変更されます。 同じ例の演算子>>は、各配列要素に対してx = x / 2 ^ zで表される出力を生成します。

In [81]:
Z <- Z

array([False, False, False, False,  True,  True,  True,  True,  True,
       False, False])

In [82]:
1j*Z

array([ 0. +0.j,  0. +1.j,  0. +2.j,  0. +3.j, -0. -4.j, -0. -5.j,
       -0. -6.j, -0. -7.j, -0. -8.j,  0. +9.j,  0.+10.j])

In [83]:
Z/1/1

array([ 0.,  1.,  2.,  3., -4., -5., -6., -7., -8.,  9., 10.])

In [84]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## 28,以下の結果は？ 

In [19]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/Users/satoutakumi/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/Users/satoutakumi/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


## 29,float型の配列の小数点以下切り下げをする方法

In [20]:
# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[10. 10. -2. 10.  5. -4.  1.  2. -3. -3.]


#http://pppurple.hatenablog.com/entry/2016/04/24/230450

## 30,二つの配列から同じ値を見つける方法

In [21]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 1 3 4 7 8]


## 31,numpyの全ての警告を無視する方法

In [22]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

SyntaxError: invalid syntax (<ipython-input-22-0437b6d2f8fa>, line 8)

## 32,以下の表現は正しいか？

In [23]:
np.sqrt(-1) == np.emath.sqrt(-1)

/Users/satoutakumi/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#https://qiita.com/adad/items/ef271572f31c9f256f24

## 33,昨日、今日、明日の日にちを得る手法

In [25]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2018-04-11
2018-04-12
2018-04-13


## 34,2016年7月に対応する全ての日時を得る手法

In [87]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

In [88]:
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


## 35, ((A+B)*(-A/2))の計算方法(コピーを使わない)

In [27]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

## 36, 乱数配列から整数部分を抜き取る5つの方法

In [28]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[2. 1. 0. 3. 6. 5. 3. 4. 8. 7.]
[2. 1. 0. 3. 6. 5. 3. 4. 8. 7.]
[2. 1. 0. 3. 6. 5. 3. 4. 8. 7.]
[2 1 0 3 6 5 3 4 8 7]
[2. 1. 0. 3. 6. 5. 3. 4. 8. 7.]


## 37,行の値が0~4の5×5行列を作成する 

In [90]:
Z = np.zeros((5,5))
Z += np.arange(5)

In [91]:
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#http://www.turbare.net/transl/scipy-lecture-notes/intro/numpy/operations.html

## 38,10個の整数を生成する関数を作成し、配列を作る際に使う

In [93]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)

In [94]:
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#https://qiita.com/ysk24ok/items/6736c8d8cc6eb06c6aa1 

## 39,0~1の値を格納したサイズ10のベクトルを作成する。（0,1は含まない）

In [97]:
Z = np.linspace(0,1,11,endpoint=False)[1:]

In [98]:
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#https://deepage.net/features/numpy-linspace.html

## 40,乱数を格納したサイズ10のベクトルを作成し、小さい順に並べる

In [100]:
Z=np.random.random(10)
Z.sort()

In [101]:
print(Z)

[0.06046249 0.06730981 0.38550556 0.39089805 0.44439181 0.48241541
 0.49474272 0.64625732 0.91967863 0.99754993]


## 41,np.sumよりも早く小さな配列要素を足し合わせる方法 

In [33]:
Z = np.arange(10)
np.add.reduce(Z)

45

##  42,二つの乱数配列A,Bが等しいか検討する

In [34]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


## 43,不変配列を作成する（読み取り専用）

In [35]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

## 44, デカルト座標を表した10×2の乱数行列を極座標に変換する

In [104]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)

In [105]:
print(R)
print(T)

[1.16791188 0.96178814 1.23498136 0.84304418 0.54835817 0.95446384
 0.74088379 0.41953257 0.87888469 1.14124029]
[0.92896744 0.24272769 0.92686252 1.56459797 0.51744512 1.24488689
 0.83929569 0.42682024 1.06519202 0.77965263]


## 45,サイズ10の乱数ベクトルを作成し、最大値を0に置き換える

In [106]:
Z = np.random.random(10)
Z[Z.argmax()] = 0

In [107]:
print(Z)

[0.21943592 0.55042106 0.62510761 0.53908636 0.23883236 0.95202745
 0.         0.92521857 0.90039051 0.94672124]


##  46,[0,1]*[0,1]の範囲にあるx,y座標の格子配列を作成する

In [112]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))

In [114]:
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


##  47,与えられた二つの配列X、Yについてコーシー行列C (Cij =1/(xi - yj))を作成する

In [39]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


## 48, それぞれのスカラー型の記号表記できる最小値、最大値を表示する

In [40]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


## 49,配列の全ての値を表示する方法

In [117]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))

In [118]:
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## 50,ベクトル内の最も近い値（与えられたスカラー量）を見つける方法

In [119]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

94


In [120]:
print(v)

94.35849287717247


#http://python-remrin.hatenadiary.jp/entry/2017/04/26/233717

## 51,位置(x,y)色(r,g,b)を表す格子配列を作る方法

In [122]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])

In [123]:
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


## 52,座標を表す100×2の乱数ベクトルを考え、それぞれの二点距離を測る

In [125]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.66008301 0.30076694 0.64058125 0.46900277 0.65652926
  0.20537084 0.4518021  0.340059   0.53722865]
 [0.66008301 0.         0.45673055 0.35775595 0.23204507 0.28892125
  0.62940078 0.46156961 0.34370074 0.60065798]
 [0.30076694 0.45673055 0.         0.34196845 0.36179154 0.58099107
  0.4165997  0.15839513 0.12657236 0.64277429]
 [0.64058125 0.35775595 0.34196845 0.         0.45712763 0.62143624
  0.71950088 0.22180668 0.32961755 0.84354824]
 [0.46900277 0.23204507 0.36179154 0.45712763 0.         0.21930778
  0.403152   0.44597672 0.23678123 0.39477355]
 [0.65652926 0.28892125 0.58099107 0.62143624 0.21930778 0.
  0.53819047 0.65496584 0.45543052 0.36544804]
 [0.20537084 0.62940078 0.4165997  0.71950088 0.403152   0.53819047
  0.         0.57434531 0.39001048 0.34064302]
 [0.4518021  0.46156961 0.15839513 0.22180668 0.44597672 0.65496584
  0.57434531 0.         0.22648092 0.77837825]
 [0.340059   0.34370074 0.12657236 0.32961755 0.23678123 0.45543052
  0.39001048 0.22648

In [126]:
# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.25980246 0.50650667 0.53210584 0.41484998 0.51643879
  0.28640869 0.25094381 0.40060059 0.97123003]
 [0.25980246 0.         0.48262332 0.36299594 0.48631876 0.26050879
  0.22123428 0.12253024 0.15351418 0.71686766]
 [0.50650667 0.48262332 0.         0.83722285 0.17985123 0.5325676
  0.26471774 0.36160751 0.5923863  0.83850632]
 [0.53210584 0.36299594 0.83722285 0.         0.84850343 0.39871671
  0.58254138 0.48451139 0.25105489 0.72884683]
 [0.41484998 0.48631876 0.17985123 0.84850343 0.         0.61681718
  0.27695525 0.36834895 0.62500997 0.98140714]
 [0.51643879 0.26050879 0.5325676  0.39871671 0.61681718 0.
  0.35171644 0.2952972  0.18279811 0.45636411]
 [0.28640869 0.22123428 0.26471774 0.58254138 0.27695525 0.35171644
  0.         0.09871261 0.34947516 0.76381913]
 [0.25094381 0.12253024 0.36160751 0.48451139 0.36834895 0.2952972
  0.09871261 0.         0.25742023 0.7359979 ]
 [0.40060059 0.15351418 0.5923863  0.25105489 0.62500997 0.18279811
  0.34947516 0.2574202

## 53,32ビットのfloat型の配列をその場で32ビットの整数配列に変更する方法

In [128]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)

In [129]:
print(Z)

[0 1 2 3 4 5 6 7 8 9]


## 54,以下のファイルはどうやって読む？

In [130]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#http://www.mwsoft.jp/programming/numpy/csv.html

## 55,numpy配列の列挙に相当するものは？

In [135]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


## 56, ジェネリック2Dガウスのような配列を生成する

In [137]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )

In [138]:
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

## 57, 二次元配列にp個の要素をランダムに配置する方法

In [142]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)

In [143]:
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## 58,行列の各行の平均を引く

In [145]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y = X - X.mean(axis=1).reshape(-1, 1)

In [146]:
print(Y)

[[-0.27717946 -0.08770204  0.35817956 -0.40513409  0.38149202  0.2099032
   0.1871897  -0.09094544  0.17118611 -0.44698955]
 [-0.02005134  0.26325792  0.1760898   0.25905879  0.20343017 -0.49723965
   0.24051147  0.01570504 -0.53723087 -0.10353133]
 [ 0.10360615 -0.20229934  0.08220397  0.05524129  0.15778023  0.01156954
  -0.03887656  0.20515434  0.10090949 -0.47528911]
 [ 0.33278974  0.00273491 -0.33867375  0.25826144 -0.46100305 -0.06573746
   0.26893275  0.10633844 -0.42170079  0.31805777]
 [ 0.28533429  0.12404112  0.28766405 -0.20249511 -0.03210263 -0.49493054
  -0.11046318 -0.06239136 -0.04598935  0.25133272]]


## 59,n番目の列によって配列を並び替える方法

In [13]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[0 9 6]
 [2 3 4]
 [7 7 7]]
[[2 3 4]
 [7 7 7]
 [0 9 6]]


## 60,与えられた二次元配列にnull列があるかどうか知る方法 

In [3]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


## 61, 配列内の与えられた値から最も近い値を探す

In [147]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]

In [148]:
print(m)

0.4802412799527497


## 62, (1,3)型と(3,1)型の配列を考え、イテレータを用いて足し算を行う

In [5]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


## 63,nameという名前の属性を持つ配列クラスを定義する

In [149]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


# クラスについて
http://diveintopython3-ja.rdy.jp/special-method-names.html

## 64, 与えられたベクトルを考え、第2のベクトルによってインデックスされた各要素に1を加える方法は（繰り返しインデックスに注意してください）？

In [161]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 2. 7. 3. 3. 2. 2. 3. 3. 2.]


In [151]:
# Another solution
np.add.at(Z, I, 1)
print(Z)

[3. 1. 5. 5. 5. 9. 5. 7. 5. 5.]


#http://python-remrin.hatenadiary.jp/entry/2017/05/22/131425

## ＊65,Xベクトルの要素をIのリストのインデックスに基づいてF配列に累積する方法

In [12]:

# Author: Alan G Isaac

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


## 66,（dtype = ubyte）の（w、h、3）画像を考慮して、固有色の数を計算する

In [152]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))

In [153]:
print(n)

8


## 67,4次元配列を考える、一度に最後の2軸を合計する方法は？ 

In [155]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)

[[49 56 50 43]
 [39 55 68 37]
 [53 39 55 61]]


In [156]:
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[49 56 50 43]
 [39 55 68 37]
 [53 39 55 61]]


## 68, 1次元ベクトルDを考える、サブセットインデックスを記述する同じサイズのベクトルSを使用してDの平均をどのように計算するのか？

In [163]:
D = np.random.uniform(0,1,100)
print(D)
S = np.random.randint(0,10,100)
print(S)
D_sums = np.bincount(S, weights=D)
print(D_sums)
D_counts = np.bincount(S)
print(D_counts)
D_means = D_sums / D_counts
print(D_means)

[0.06137041 0.88001499 0.09441073 0.60167497 0.44719407 0.35529496
 0.27629237 0.39408453 0.46050032 0.91976303 0.6043148  0.82896728
 0.12656435 0.57769984 0.10207464 0.73999831 0.23691037 0.48358641
 0.71948825 0.78320427 0.62969842 0.60239248 0.1036232  0.90576211
 0.66035614 0.27098025 0.57646796 0.60458456 0.66718572 0.19774137
 0.72362383 0.82824683 0.45805024 0.82523307 0.91246445 0.15091313
 0.65364925 0.16922755 0.46973927 0.60395717 0.51251136 0.81652843
 0.65041972 0.32488635 0.70307458 0.96548832 0.27254566 0.78687975
 0.25608291 0.06105133 0.43952307 0.36522445 0.58190512 0.47402675
 0.10143686 0.96087071 0.66824724 0.2281756  0.59214328 0.61484125
 0.24322748 0.56335684 0.04534432 0.36244259 0.75620488 0.11777541
 0.39256924 0.89555546 0.1805178  0.44433228 0.94630113 0.92506233
 0.93495088 0.42678254 0.79070793 0.73510681 0.37695056 0.3467984
 0.24635508 0.07869973 0.50256915 0.16948496 0.7150101  0.29268697
 0.89803181 0.2870579  0.69720207 0.03396369 0.20460133 0.90810

In [164]:
# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

0    0.589423
1    0.567510
2    0.513593
3    0.516775
4    0.551910
5    0.482692
6    0.450483
7    0.353572
8    0.479592
9    0.364113
dtype: float64


## 69,内積の対角をどうやって取得するか

In [165]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.81785546, 1.03366523, 0.63182738, 1.67085402, 1.34381058])

## 70, ベクトル[1、2、3、4、5]、各値の間に3つの連続するゼロが挿入された新しいベクトルを構築する方法を考えてみましょう。

In [169]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z

In [170]:
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


## 71,次元（5,5,3）の配列を考えて、それを次元（5,5）の配列で掛けるにはどうするか？ 


In [167]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


## 72, 配列の2つの行を交換するには？

In [171]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]

In [172]:
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## 73, 10個の三角形（共有された頂点を持つ）を記述する10個の三つ組の集合を考え、すべての三角形を構成する一意の線分の集合を見つける

In [183]:
# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
#print(faces)
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
#print(F)
F = F.reshape(len(F)*3,2)
#print(F)
F = np.sort(F,axis=1)
#print(F)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
#print(G)
G = np.unique(G)

In [184]:
print(G)

[( 9, 27) ( 9, 29) (15, 28) (15, 81) (15, 98) (16, 41) (16, 57) (20, 34)
 (20, 44) (24, 27) (24, 48) (27, 29) (27, 48) (28, 98) (32, 38) (32, 44)
 (34, 44) (38, 44) (40, 44) (40, 95) (41, 57) (44, 95) (53, 59) (53, 76)
 (54, 57) (54, 82) (57, 82) (59, 76) (81, 98)]


#https://qiita.com/supersaiakujin/items/c580f2aae90818150b35

## 74,与えられた配列Cがbincountである場合、np.bincount（A）== Cのような配列Aを生成する方法は？

In [185]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


## 75, 