## 100 numpy exercises

# 初心者向けサイト
http://wbhappy.hatenablog.jp/entry/2015/02/06/210000
http://rest-term.com/archives/2999/
https://qiita.com/takaaki5564/items/451d9d6c319f76758a9d

## 1,numpyパッケージをnpの名前でインポート

In [1]:
import numpy as np

## 2,numpyのバージョンと構造を表示

In [23]:
print(np.__version__)
np.show_config()

1.14.0
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/satoutakumi/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/satoutakumi/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/satoutakumi/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/satoutakumi/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/satoutakumi/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/satoutakumi/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/satoutakumi/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/satoutakumi/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
 

## 3,サイズ10のゼロベクトルを作成する

In [24]:
z=np.zeros(10)

In [25]:
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 4,配列のメモリ容量を見る

In [26]:
Z=np.zeros((10,10))

In [27]:
print("%d bytes"%(Z.size*Z.itemsize))

800 bytes


## 5,コマンドラインからnumpy add関数のドキュメントを取得する方法は？

In [28]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


## 6,5つ目の要素が1で、他の値が0であるサイズ10のベクトルを作成する

In [29]:
Z=np.zeros(10)
Z[4]=1

In [30]:
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 7,10から49までの要素を持つベクトルを作成

In [31]:
Z=np.arange(10,50)

In [32]:
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 8,ベクトル要素を逆転させる

In [33]:
Z=np.arange(50)
Z=Z[::-1]

In [34]:
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


## 9,0から8を要素に持つ3×3の行列を作成する

In [35]:
Z=np.arange(9).reshape(3,3)

In [36]:
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 10,0ではない要素を検索する

In [37]:
nz=np.nonzero([1,2,0,0,4,0])

In [38]:
print(nz)

(array([0, 1, 4]),)


## 11,3×3の単位行列を作成する

In [39]:
Z=np.eye(3)

In [40]:
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 12,3×3×3の乱数要素の配列を作成する

In [41]:
Z=np.random.random((3,3,3))

In [42]:
print(Z)

[[[0.38925276 0.86160688 0.02385085]
  [0.40970073 0.20277487 0.29674776]
  [0.34110271 0.94933443 0.31934558]]

 [[0.51194152 0.78023576 0.43301915]
  [0.47597502 0.75766881 0.18587104]
  [0.69490371 0.9942655  0.96329408]]

 [[0.37917421 0.47971864 0.22664136]
  [0.82506289 0.0875077  0.02810746]
  [0.84287828 0.90379182 0.89711909]]]


## 13, 10×10の乱数要素配列を作成し、最大値、最小値を検索する

In [43]:
Z=np.random.random((10,10))
Zmin,Zmax=Z.min(),Z.max()

In [44]:
print(Zmin,Zmax)

0.029847868777930886 0.9924484121468836


## 14,大きさ30の乱数ベクトルを作成し、その平均をとる

In [45]:
Z=np.random.random(30)
m=Z.mean()

In [46]:
print(m)

0.5560389555571262


## 15, 縁が1 、内部が0の二次元配列を作成する

In [47]:
Z=np.ones((10,10))
Z[1:-1,1:-1]=0

In [48]:
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 16, 既存の配列の縁に0の縁を追加する

In [49]:
Z=np.ones((5,5))
Z=np.pad(Z,pad_width=1,mode='constant',constant_values=0)

In [50]:
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## 17,以下の表記の結果は？

In [51]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)

nan
False
False
nan
False


## 18,対角項の一つ下の値が1,2,3,4である5×5の行列を作成する

In [52]:
Z=np.diag(1+np.arange(4),k=-1)

In [53]:
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## 19, 8×8の行列を作成し、市松模様で埋める

In [54]:
Z=np.zeros((8,8),dtype=int)
Z[1::2,::2]=1
Z[::2,1::2]=1

In [55]:
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 20,(6,7,8)の型の配列を考えた時、100番目の(x,y,z)の要素は？

In [56]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


## 21,tile関数を用いて8×8の市松模様行列を作る

In [57]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))

In [58]:
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 22,5×5の乱数行列を規格化する

In [59]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)

In [60]:
print(Z)

[[0.6156067  0.33320674 0.4595616  1.         0.38794532]
 [0.86358872 0.25518285 0.28860251 0.56685229 0.        ]
 [0.92309287 0.84153286 0.62601739 0.02100213 0.88072675]
 [0.34299626 0.79059073 0.74214215 0.95759934 0.18074143]
 [0.94818651 0.54210078 0.39708704 0.9798986  0.22947166]]


## 23,色を4つの符号なしバイト（RGBA）として記述するカスタムdtypeを作成

In [61]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

## 24,5×3の行列と3×2の行列をかける

In [62]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))

In [63]:
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [64]:
# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))

##  25,与えられた一次元配列の3~8要素の符号を変える

In [65]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1

In [66]:
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


## 26,以下のスクリプトの結果は？

In [67]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#https://stackoverflow.com/questions/42955201/python-numpy-range-and-sum-1?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

#最初の行は、0 + 1 + 2 + 3 + 4 +（ - 1）と等価です。 3行目は、軸= -1で0 + 1 + 2 + 3 + 4に相当します。

## 27,整数ベクトルを考えた時、以下のどの表記が正しいか

In [68]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: Integers to negative integer powers are not allowed.

In [69]:
Z**Z

ValueError: Integers to negative integer powers are not allowed.

In [70]:
2 << Z >> 2

array([                 0,                  1,                  2,
                        4, 576460752303423488, 288230376151711744,
       144115188075855872,  72057594037927936,  36028797018963968,
                      256,                512])

#https://stackoverflow.com/questions/38491204/numpy-and-operators
#演算子<<と>>はビットシフト演算子です（それぞれ左と右です）。 特定の例（<<付き）では、配列要素ごとにx = x * 2 ^ zを実行しています。その結果、出力が変更されます。 同じ例の演算子>>は、各配列要素に対してx = x / 2 ^ zで表される出力を生成します。

In [71]:
Z <- Z

array([False, False, False, False,  True,  True,  True,  True,  True,
       False, False])

In [72]:
1j*Z

array([ 0. +0.j,  0. +1.j,  0. +2.j,  0. +3.j, -0. -4.j, -0. -5.j,
       -0. -6.j, -0. -7.j, -0. -8.j,  0. +9.j,  0.+10.j])

In [73]:
Z/1/1

array([ 0.,  1.,  2.,  3., -4., -5., -6., -7., -8.,  9., 10.])

In [74]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## 28,以下の結果は？ 

In [75]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/Users/satoutakumi/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/Users/satoutakumi/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


## 29,float型の配列の小数点以下切り下げをする方法

In [76]:
# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[-1.  7.  4. -1. -6. -7. -1. -5. -9.  7.]


#http://pppurple.hatenablog.com/entry/2016/04/24/230450

## 30,二つの配列から同じ値を見つける方法

In [77]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 2 4 6 8 9]


## 31,numpyの全ての警告を無視する方法

In [78]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

SyntaxError: invalid syntax (<ipython-input-78-0437b6d2f8fa>, line 8)

## 32,以下の表現は正しいか？

In [79]:
np.sqrt(-1) == np.emath.sqrt(-1)

/Users/satoutakumi/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#https://qiita.com/adad/items/ef271572f31c9f256f24

## 33,昨日、今日、明日の日にちを得る手法

In [80]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2018-04-19
2018-04-20
2018-04-21


## 34,2016年7月に対応する全ての日時を得る手法

In [81]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

In [82]:
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


## 35, ((A+B)*(-A/2))の計算方法(コピーを使わない)

In [83]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

## 36, 乱数配列から整数部分を抜き取る5つの方法

In [84]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[5. 2. 7. 0. 5. 9. 2. 4. 5. 8.]
[5. 2. 7. 0. 5. 9. 2. 4. 5. 8.]
[5. 2. 7. 0. 5. 9. 2. 4. 5. 8.]
[5 2 7 0 5 9 2 4 5 8]
[5. 2. 7. 0. 5. 9. 2. 4. 5. 8.]


## 37,行の値が0~4の5×5行列を作成する 

In [85]:
Z = np.zeros((5,5))
Z += np.arange(5)

In [86]:
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#http://www.turbare.net/transl/scipy-lecture-notes/intro/numpy/operations.html

## 38,10個の整数を生成する関数を作成し、配列を作る際に使う

In [87]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)

In [88]:
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#https://qiita.com/ysk24ok/items/6736c8d8cc6eb06c6aa1 

## 39,0~1の値を格納したサイズ10のベクトルを作成する。（0,1は含まない）

In [89]:
Z = np.linspace(0,1,11,endpoint=False)[1:]

In [90]:
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#https://deepage.net/features/numpy-linspace.html

## 40,乱数を格納したサイズ10のベクトルを作成し、小さい順に並べる

In [91]:
Z=np.random.random(10)
Z.sort()

In [92]:
print(Z)

[0.1345391  0.13861694 0.19099398 0.26476353 0.57176515 0.60817453
 0.71657337 0.81330463 0.89254745 0.92333718]


## 41,np.sumよりも早く小さな配列要素を足し合わせる方法 

In [93]:
Z = np.arange(10)
np.add.reduce(Z)

45

##  42,二つの乱数配列A,Bが等しいか検討する

In [94]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


## 43,不変配列を作成する（読み取り専用）

In [95]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

## 44, デカルト座標を表した10×2の乱数行列を極座標に変換する

In [96]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)

In [97]:
print(R)
print(T)

[0.37805061 0.74915366 0.08770425 0.69247495 0.98660788 1.13825454
 0.84754804 0.21901634 0.96271833 1.24402437]
[0.35886539 1.12198692 1.24653513 0.55668424 0.03423654 0.70221317
 0.24184924 0.80518861 0.92191621 0.74504703]


## 45,サイズ10の乱数ベクトルを作成し、最大値を0に置き換える

In [98]:
Z = np.random.random(10)
Z[Z.argmax()] = 0

In [99]:
print(Z)

[0.04096187 0.89801083 0.57547311 0.03911641 0.3863805  0.42200698
 0.33069046 0.         0.76153396 0.77812976]


##  46,[0,1]*[0,1]の範囲にあるx,y座標の格子配列を作成する

In [100]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))

In [101]:
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


##  47,与えられた二つの配列X、Yについてコーシー行列C (Cij =1/(xi - yj))を作成する

In [102]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


## 48, それぞれのスカラー型の記号表記できる最小値、最大値を表示する

In [103]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


## 49,配列の全ての値を表示する方法

In [104]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))

In [105]:
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## 50,ベクトル内の最も近い値（与えられたスカラー量）を見つける方法

In [106]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

88


In [107]:
print(v)

87.87397582372404


#http://python-remrin.hatenadiary.jp/entry/2017/04/26/233717

## 51,位置(x,y)色(r,g,b)を表す格子配列を作る方法

In [108]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])

In [109]:
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


## 52,座標を表す100×2の乱数ベクトルを考え、それぞれの二点距離を測る

In [110]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.56572374 0.57034832 0.74687152 0.51101354 0.59691654
  0.5482123  0.52268108 0.2590691  0.21903055]
 [0.56572374 0.         1.06971125 0.75277288 0.82474692 0.50342099
  1.02641482 0.41980399 0.63445437 0.35353665]
 [0.57034832 1.06971125 0.         0.78952471 0.38081604 0.82133347
  0.06598921 0.80958289 0.4396266  0.72917859]
 [0.74687152 0.75277288 0.78952471 0.         0.40976132 0.24937315
  0.72363185 0.33699789 0.52260436 0.65429948]
 [0.51101354 0.82474692 0.38081604 0.40976132 0.         0.46287908
  0.31526843 0.47503391 0.25567416 0.55095144]
 [0.59691654 0.50342099 0.82133347 0.24937315 0.46287908 0.
  0.75993264 0.09491727 0.43906221 0.45145382]
 [0.5482123  1.02641482 0.06598921 0.72363185 0.31526843 0.75993264
  0.         0.75152731 0.39258997 0.69227036]
 [0.52268108 0.41980399 0.80958289 0.33699789 0.47503391 0.09491727
  0.75152731 0.         0.39819302 0.36203305]
 [0.2590691  0.63445437 0.4396266  0.52260436 0.25567416 0.43906221
  0.39258997 0.39819

In [111]:
# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.51608499 0.41415525 0.77658958 0.27445122 0.39772422
  0.26770809 0.53395517 0.85910405 0.72344335]
 [0.51608499 0.         0.22116749 0.51476004 0.24164149 0.430357
  0.62049754 0.34558371 0.55656535 0.466421  ]
 [0.41415525 0.22116749 0.         0.71311489 0.20122516 0.20955892
  0.43227124 0.16507468 0.76543013 0.66095397]
 [0.77658958 0.51476004 0.71311489 0.         0.59626772 0.90517887
  0.99860029 0.85800013 0.09059338 0.05496448]
 [0.27445122 0.24164149 0.20122516 0.59626772 0.         0.32733826
  0.41560965 0.36279564 0.66519082 0.54139981]
 [0.39772422 0.430357   0.20955892 0.90517887 0.32733826 0.
  0.28367909 0.18688498 0.9639913  0.85142704]
 [0.26770809 0.62049754 0.43227124 0.99860029 0.41560965 0.28367909
  0.         0.46901582 1.07366866 0.94381567]
 [0.53395517 0.34558371 0.16507468 0.85800013 0.36279564 0.18688498
  0.46901582 0.         0.90214904 0.80787803]
 [0.85910405 0.55656535 0.76543013 0.09059338 0.66519082 0.9639913
  1.07366866 0.90214904

## 53,32ビットのfloat型の配列をその場で32ビットの整数配列に変更する方法

In [112]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)

In [113]:
print(Z)

[0 1 2 3 4 5 6 7 8 9]


## 54,以下のファイルはどうやって読む？

In [114]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#http://www.mwsoft.jp/programming/numpy/csv.html

## 55,numpy配列の列挙に相当するものは？

In [115]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


## 56, ジェネリック2Dガウスのような配列を生成する

In [116]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )

In [117]:
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

## 57, 二次元配列にp個の要素をランダムに配置する方法

In [118]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)

In [119]:
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## 58,行列の各行の平均を引く

In [120]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y = X - X.mean(axis=1).reshape(-1, 1)

In [121]:
print(Y)

[[-0.42252118 -0.00436199 -0.0092597  -0.19426188 -0.13849152 -0.29971739
   0.3775168   0.23789409  0.16788287  0.2853199 ]
 [ 0.39222843 -0.1436083  -0.12963413 -0.0968266  -0.45884746  0.18022203
  -0.03053027  0.15800419  0.35245398 -0.22346187]
 [ 0.37906358 -0.28863337 -0.29473635 -0.13056251 -0.18175491 -0.14049785
   0.42859346 -0.31757172 -0.02790984  0.5740095 ]
 [ 0.14550439 -0.20123427  0.11645683 -0.29700285  0.20769026  0.33530044
   0.08750432 -0.09378844  0.00549375 -0.30592444]
 [-0.03485865 -0.25956041  0.3929073  -0.07765083  0.41623596 -0.3464231
   0.32809162  0.08127524 -0.46378399 -0.03623315]]


## 59,n番目の列によって配列を並び替える方法

In [122]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[3 9 6]
 [4 4 6]
 [1 1 3]]
[[1 1 3]
 [4 4 6]
 [3 9 6]]


## 60,与えられた二次元配列にnull列があるかどうか知る方法 

In [123]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


## 61, 配列内の与えられた値から最も近い値を探す

In [124]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]

In [125]:
print(m)

0.46839250312039693


## 62, (1,3)型と(3,1)型の配列を考え、イテレータを用いて足し算を行う

In [126]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


## 63,nameという名前の属性を持つ配列クラスを定義する

In [127]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


# クラスについて
http://diveintopython3-ja.rdy.jp/special-method-names.html

## 64, 与えられたベクトルを考え、第2のベクトルによってインデックスされた各要素に1を加える方法は（繰り返しインデックスに注意してください）？

In [128]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[6. 2. 1. 3. 6. 1. 3. 4. 3. 1.]


In [129]:
# Another solution
np.add.at(Z, I, 1)
print(Z)

[11.  3.  1.  5. 11.  1.  5.  7.  5.  1.]


#http://python-remrin.hatenadiary.jp/entry/2017/05/22/131425

## ＊65,Xベクトルの要素をIのリストのインデックスに基づいてF配列に累積する方法

In [130]:

# Author: Alan G Isaac

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


## 66,（dtype = ubyte）の（w、h、3）画像を考慮して、固有色の数を計算する

In [131]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))

In [132]:
print(n)

8


## 67,4次元配列を考える、一度に最後の2軸を合計する方法は？ 

In [133]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)

[[67 69 57 32]
 [41 49 46 73]
 [66 54 54 64]]


In [134]:
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[67 69 57 32]
 [41 49 46 73]
 [66 54 54 64]]


## 68, 1次元ベクトルDを考える、サブセットインデックスを記述する同じサイズのベクトルSを使用してDの平均をどのように計算するのか？

In [135]:
D = np.random.uniform(0,1,100)
print(D)
S = np.random.randint(0,10,100)
print(S)
D_sums = np.bincount(S, weights=D)
print(D_sums)
D_counts = np.bincount(S)
print(D_counts)
D_means = D_sums / D_counts
print(D_means)

[0.3818913  0.60674096 0.97098367 0.45397731 0.81380956 0.50289056
 0.21110266 0.98102351 0.78489774 0.01712462 0.4433563  0.07219064
 0.28229426 0.27155865 0.23351768 0.6537107  0.77308693 0.8138664
 0.77569155 0.50911226 0.7117019  0.44188455 0.27405477 0.77040816
 0.66612853 0.33003984 0.80406209 0.85205936 0.60849808 0.71022009
 0.83647452 0.64603686 0.0209603  0.89325005 0.31921409 0.43559237
 0.3945276  0.05708149 0.20181535 0.47355938 0.86076651 0.72960726
 0.07711722 0.81145466 0.9682951  0.52638564 0.02659069 0.90075838
 0.3557758  0.9720497  0.52232269 0.12947102 0.63082112 0.32375442
 0.74409527 0.41788045 0.7223206  0.45771661 0.96632463 0.84889134
 0.681028   0.50877457 0.00920611 0.68410509 0.71559851 0.46334196
 0.96366533 0.01983616 0.79053735 0.77490454 0.61691558 0.56646742
 0.82382468 0.99509884 0.33217889 0.69770843 0.01297897 0.88808303
 0.24058108 0.90494838 0.31361656 0.796387   0.44512962 0.14368851
 0.60190754 0.34553472 0.0552929  0.76588128 0.719426   0.36393

In [136]:
# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

0    0.616792
1    0.562104
2    0.470102
3    0.529388
4    0.626434
5    0.568032
6    0.470847
7    0.508120
8    0.583039
9    0.440325
dtype: float64


## 69,内積の対角をどうやって取得するか

In [137]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.126243  , 0.8367808 , 0.7899202 , 1.12258379, 0.96920712])

## 70, ベクトル[1、2、3、4、5]、各値の間に3つの連続するゼロが挿入された新しいベクトルを構築する方法を考えてみましょう。

In [138]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z

In [139]:
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


## 71,次元（5,5,3）の配列を考えて、それを次元（5,5）の配列で掛けるにはどうするか？ 


In [140]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


## 72, 配列の2つの行を交換するには？

In [141]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]

In [142]:
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## 73, 10個の三角形（共有された頂点を持つ）を記述する10個の三つ組の集合を考え、すべての三角形を構成する一意の線分の集合を見つける

In [143]:
# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
#print(faces)
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
#print(F)
F = F.reshape(len(F)*3,2)
#print(F)
F = np.sort(F,axis=1)
#print(F)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
#print(G)
G = np.unique(G)

In [144]:
print(G)

[( 0, 40) ( 0, 48) ( 1, 67) ( 1, 73) ( 3, 52) ( 3, 87) (18, 53) (18, 82)
 (24, 42) (24, 97) (26, 27) (26, 42) (27, 42) (34, 44) (34, 57) (40, 48)
 (42, 97) (44, 57) (52, 87) (53, 82) (54, 56) (54, 99) (56, 99) (58, 88)
 (58, 93) (67, 73) (81, 87) (81, 98) (87, 98) (88, 93)]


#https://qiita.com/supersaiakujin/items/c580f2aae90818150b35

## 74,与えられた配列Cがbincountである場合、np.bincount（A）== Cのような配列Aを生成する方法は？

In [145]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


## 75,配列上のスライドウィンドウを使って平均を計算するには？ 

In [146]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    print(ret)
    ret[n:] = ret[n:] - ret[:-n]
    print(ret)
    return ret[n - 1:] / n
Z = np.arange(20)


In [147]:
print(moving_average(Z, n=3))

[  0.   1.   3.   6.  10.  15.  21.  28.  36.  45.  55.  66.  78.  91.
 105. 120. 136. 153. 171. 190.]
[ 0.  1.  3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33. 36. 39. 42. 45. 48.
 51. 54.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#https://deepage.net/features/numpy-diff.html

## 76,最初の行が（Z [0]、Z [1]、Z [2]）であり、後続の各行が1だけシフトされた2次元配列を構築する1次元配列Zを考える（最後の行は（Z [ -3]、Z [-2]、Z [-1]）

In [148]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)

In [149]:
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


## 77,ブール値を無効にする方法、または浮動小数点数の符号を変更する方法は？

In [150]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.47983049, -0.18799656, -0.70148463,  0.09188377, -0.98693014,
       -0.8206904 ,  0.27414439, -0.95953779, -0.55921761, -0.69715692,
        0.14563991,  0.93772679, -0.74656576, -0.93518365,  0.89962526,
        0.68876801,  0.57436016, -0.05102777,  0.49314316,  0.41796454,
        0.16333062,  0.14743025, -0.25517962,  0.27229169, -0.04592217,
       -0.75729522, -0.92273849, -0.45150222, -0.43727988,  0.10974315,
        0.2584932 , -0.93118762, -0.09967247,  0.03143934,  0.49627733,
        0.65884542,  0.32088817, -0.88162044,  0.0518069 ,  0.41492117,
       -0.09157802, -0.79433294, -0.45897779,  0.11880687,  0.45695637,
        0.06133065, -0.35065872, -0.10872674,  0.19835055,  0.12395041,
        0.79976755,  0.15316793,  0.3659021 ,  0.45648021,  0.58751288,
       -0.13729166, -0.34217352, -0.40005363,  0.99562577, -0.44737329,
        0.22386101,  0.9062618 ,  0.4434933 ,  0.6876912 , -0.54235989,
       -0.34073057,  0.76795761,  0.02352541,  0.00471864, -0.34

## 78, 線（2d）と点pを記述する2組の点P0、P1を考える、pから各線i（P0 [i]、P1 [i]）までの距離を計算する方法を検討する。

In [151]:
def distance(P0, P1, p):
    T = P1 - P0
    print(T)
    L = (T**2).sum(axis=1)
    print(L)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

In [152]:
print(distance(P0, P1, p))

[[  5.18152473  -7.33314133]
 [-11.54420399  -2.07168153]
 [ 11.94480141   7.05783255]
 [ -2.70104459  -0.60382798]
 [  8.47052496   7.94616566]
 [ -2.06974547 -10.81680832]
 [  5.64359384   9.10168273]
 [ 15.45569076  -7.15086377]
 [  2.06126245  -8.81236459]
 [-10.73691008   0.62278319]]
[ 80.62316025 137.56051012 192.49128098   7.66025011 134.89134168
 121.28718854 114.69077998 290.01322943  81.9065726  115.66909706]
[ 9.51141219  1.29498917  2.50399794 12.19923561  5.80708287  8.60216266
  7.73115428  5.10358309  8.17227756 11.30694532]


## 79,各点j（P [j]）から各線i（P0 [i]、P1 [i]）までの距離を計算する手法について、線（2d）および点の集合Pを記述する点P0、P1の2組を考える。

In [153]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))


[[ 9.39706121  1.26713526]
 [ 0.62868622  8.61402798]
 [-2.25509657 -7.60910274]
 [-3.73323437 13.03645541]
 [-8.41692989  1.11349698]
 [-6.35315398 -7.00931785]
 [ 1.6715149   9.95708657]
 [ 4.15209476  4.5852115 ]
 [-8.88627059 -7.60714185]
 [-7.36850579 -6.05853803]]
[ 89.91039122  74.59672445  62.98390505 183.88620856  72.08458427
  89.4931021  101.93753508  38.26405536 136.83441202  91.0007606 ]
[[ 9.39706121  1.26713526]
 [ 0.62868622  8.61402798]
 [-2.25509657 -7.60910274]
 [-3.73323437 13.03645541]
 [-8.41692989  1.11349698]
 [-6.35315398 -7.00931785]
 [ 1.6715149   9.95708657]
 [ 4.15209476  4.5852115 ]
 [-8.88627059 -7.60714185]
 [-7.36850579 -6.05853803]]
[ 89.91039122  74.59672445  62.98390505 183.88620856  72.08458427
  89.4931021  101.93753508  38.26405536 136.83441202  91.0007606 ]
[[ 9.39706121  1.26713526]
 [ 0.62868622  8.61402798]
 [-2.25509657 -7.60910274]
 [-3.73323437 13.03645541]
 [-8.41692989  1.11349698]
 [-6.35315398 -7.00931785]
 [ 1.6715149   9.95708657]
 [ 

## 80, 任意の配列を考えて、固定された形状を持つサブパーツを抽出し、与えられた要素の中央に置く（必要に応じて塗りつぶし値を持つパッド）関数を記述する。

In [154]:

# Author: Nicolas Rougier

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]

In [155]:
print(Z)
print(R)

[[7 7 8 4 6 0 7 4 0 8]
 [1 4 5 8 1 5 1 8 8 8]
 [6 5 1 5 8 5 2 4 5 5]
 [2 4 5 7 7 9 9 6 1 7]
 [1 2 4 6 5 4 2 8 1 6]
 [3 9 1 3 7 5 3 4 1 2]
 [3 6 3 0 8 2 6 8 4 8]
 [1 3 5 2 6 3 0 3 0 0]
 [8 6 0 4 6 3 1 5 3 8]
 [4 8 6 8 3 0 8 6 4 4]]
[[0 0 0 0 0]
 [0 7 7 8 4]
 [0 1 4 5 8]
 [0 6 5 1 5]
 [0 2 4 5 7]]


## 81,配列Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]について、配列R = [[1,2,3、 4]、[2,3,4,5]、[3,4,5,6]、...、[11,12,13,14]]を作成する？

In [156]:

# Author: Stefan van der Walt

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))

In [157]:
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#https://qiita.com/daimonji-bucket/items/7d04a9687e7714d6216b

## 82,行列のランクを計算する 

In [158]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)

In [159]:
print(rank)

10


#https://qiita.com/kyoro1/items/4df11e933e737703d549 

## 83, 配列内で最も含まれる値を見つける方法は？

In [160]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

5


## 84,乱数の入った10x10行列からすべての連続した3x3ブロックを抽出する

In [161]:
Z = np.random.randint(0,5,(10,10))
print(Z)
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)

[[0 4 0 2 4 3 0 2 1 0]
 [0 1 4 2 2 2 2 2 4 0]
 [0 1 3 4 4 2 0 3 1 1]
 [1 2 0 0 3 2 2 3 4 4]
 [4 1 4 1 3 3 0 0 0 2]
 [1 1 1 4 2 3 2 2 3 4]
 [4 1 0 1 1 3 4 2 3 1]
 [3 3 2 0 2 1 4 4 2 1]
 [1 1 1 3 3 3 1 3 1 4]
 [3 1 2 3 1 1 3 4 4 4]]


In [162]:
print(C)

[[[[0 4 0]
   [0 1 4]
   [0 1 3]]

  [[4 0 2]
   [1 4 2]
   [1 3 4]]

  [[0 2 4]
   [4 2 2]
   [3 4 4]]

  [[2 4 3]
   [2 2 2]
   [4 4 2]]

  [[4 3 0]
   [2 2 2]
   [4 2 0]]

  [[3 0 2]
   [2 2 2]
   [2 0 3]]

  [[0 2 1]
   [2 2 4]
   [0 3 1]]

  [[2 1 0]
   [2 4 0]
   [3 1 1]]]


 [[[0 1 4]
   [0 1 3]
   [1 2 0]]

  [[1 4 2]
   [1 3 4]
   [2 0 0]]

  [[4 2 2]
   [3 4 4]
   [0 0 3]]

  [[2 2 2]
   [4 4 2]
   [0 3 2]]

  [[2 2 2]
   [4 2 0]
   [3 2 2]]

  [[2 2 2]
   [2 0 3]
   [2 2 3]]

  [[2 2 4]
   [0 3 1]
   [2 3 4]]

  [[2 4 0]
   [3 1 1]
   [3 4 4]]]


 [[[0 1 3]
   [1 2 0]
   [4 1 4]]

  [[1 3 4]
   [2 0 0]
   [1 4 1]]

  [[3 4 4]
   [0 0 3]
   [4 1 3]]

  [[4 4 2]
   [0 3 2]
   [1 3 3]]

  [[4 2 0]
   [3 2 2]
   [3 3 0]]

  [[2 0 3]
   [2 2 3]
   [3 0 0]]

  [[0 3 1]
   [2 3 4]
   [0 0 0]]

  [[3 1 1]
   [3 4 4]
   [0 0 2]]]


 [[[1 2 0]
   [4 1 4]
   [1 1 1]]

  [[2 0 0]
   [1 4 1]
   [1 1 4]]

  [[0 0 3]
   [4 1 3]
   [1 4 2]]

  [[0 3 2]
   [1 3 3]
   [4 2 3]]

  [[3 2 2]
   

## 85, Z [i、j] == Z [j、i]となるような2次元配列サブクラスを作成する

In [163]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42

In [164]:
print(S)

[[ 1 15 13 13  5]
 [15  7  5  8 13]
 [13  5  6 42  6]
 [13  8 42  6  5]
 [ 5 13  6  5  8]]


## 86,形状（n、n）のp行列の集合と形状（n、1）のpベクトルの集合を考える。 一度にp個の行列積の総和を計算するには？ （結果は（n、1）型を持つ） 

In [165]:
# Author: Stefan van der Walt

p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

In [166]:
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


## 87,ブロック・サム（ブロック・サイズは4x4）を得るには、16x16配列を考えてみてください。

In [167]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [168]:
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


## 88,numpy配列を使ってライフゲームを実装するには？ 

In [169]:
# Author: Nicolas Rougier

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)

In [170]:
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1

#https://ja.wikipedia.org/wiki/ライフゲーム

## 89,配列のn番目に大きい値までを取得する方法

In [171]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

In [172]:
# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])



[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


## 90, 任意の数のベクトルが与えられれば、デカルト積（すべてのアイテムのすべての組み合わせ）を構築する

In [173]:
# Author: Stefan Van der Walt

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix


In [174]:
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


## 91,通常の配列からレコード配列を作成するには？

In [175]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')

In [176]:
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


## 92,大きなベクトルZを考え、Zを3のべき乗に3つの異なる方法を使って計算する

In [179]:
# Author: Ryan G.

x = np.random.rand(5e+7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

TypeError: 'float' object cannot be interpreted as an integer

## 93,形状（8,3）および（2,2）の2つの配列AおよびBを考える。 Bの要素の順序に関係なく、Bの各行の要素を含むAの行を見つける方法は？

In [180]:
# Author: Gabe Schwartz

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]


In [181]:
print(rows)

[0 1 2 6]


## 94,10x3の行列を考えると、等しくない値（例えば[2,2,3]）の行を抽出する

In [182]:
# Author: Robert Kern

Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 1 4]
 [0 3 1]
 [0 3 1]
 [0 1 3]
 [0 0 2]
 [4 3 1]
 [4 2 2]
 [4 0 1]
 [3 1 2]
 [2 2 4]]
[[2 1 4]
 [0 3 1]
 [0 3 1]
 [0 1 3]
 [0 0 2]
 [4 3 1]
 [4 2 2]
 [4 0 1]
 [3 1 2]
 [2 2 4]]
[[2 1 4]
 [0 3 1]
 [0 3 1]
 [0 1 3]
 [0 0 2]
 [4 3 1]
 [4 2 2]
 [4 0 1]
 [3 1 2]
 [2 2 4]]


## 95,intのベクトルを行列の二進数表現に変換する

In [185]:
# Author: Warren Weckesser

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [186]:
# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


## 96,与えられた2次元配列、ユニークな行を抽出する方法は？

In [187]:
# Author: Jaime Fernández del Río

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]

In [188]:
print(uZ)

[[0 0 1]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


## 97, 2つのベクトルAとBを考慮して、内積、外積、合計、およびmul関数のeinsum相当量を書いてください

In [189]:
# Author: Alex Riley
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)


array([[0.46597516, 0.07465723, 0.57932025, 0.53085536, 0.13801982,
        0.61102646, 0.36148444, 0.42933441, 0.56053633, 0.23596345],
       [0.15342724, 0.02458168, 0.19074731, 0.17478973, 0.04544448,
        0.20118691, 0.11902257, 0.14136289, 0.1845625 , 0.07769345],
       [0.35622288, 0.05707302, 0.44287152, 0.40582169, 0.10551167,
        0.46710988, 0.27634312, 0.32821222, 0.42851182, 0.18038639],
       [0.35144246, 0.05630712, 0.4369283 , 0.40037567, 0.10409573,
        0.46084139, 0.27263467, 0.3238077 , 0.42276131, 0.17796565],
       [0.1242855 , 0.01991267, 0.15451705, 0.14159043, 0.03681283,
        0.16297377, 0.0964156 , 0.11451263, 0.14950697, 0.06293648],
       [0.38820353, 0.06219688, 0.48263124, 0.44225518, 0.1149842 ,
        0.50904565, 0.3011524 , 0.35767816, 0.46698237, 0.19658096],
       [0.36742993, 0.05886859, 0.4568046 , 0.41858915, 0.10883115,
        0.48180552, 0.28503709, 0.33853803, 0.44199313, 0.18606149],
       [0.33952707, 0.05439807, 0.4221145

## 98, 2つのベクトル（X、Y）によって記述される経路を考慮して、等距離サンプルを使用してサンプルをどのようにサンプリングするか

In [190]:
# Author: Bas Swinckels

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

## 99, 整数nおよび2次元配列Xが与えられると、n度の多項分布、すなわち整数のみを含み、nの和をとる行からの描画と解釈できる行をXから選択する。

In [191]:
# Author: Evgeni Burovski

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])


[[2. 0. 1. 1.]]


## 100,1D配列Xの平均に対するブートストラップされた95％信頼区間を計算する（すなわち、置換のN倍で配列の要素を再サンプリングし、各サンプルの平均を計算し、平均に対するパーセンタイルを計算する）。 

In [192]:
# Author: Jessica B. Hamrick

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.35708126  0.03143721]


In [ ]:
ß